### ISSUE TITLE
Run Train Example raise error "Box" object is not iterable

### ISSUE THREAD

**Issue by 945716994** [Shanghai-Digital-Brain-Laboratory/DB-Football#4]
run the main_pbt.py get a TypeError: "Box" object is not iterable. 
**Note: I change the gym to gymnasium.**

**The Traceback as follow**
Traceback (most recent call last):
  File "/home/zhp/code/DB-Football/light_malib/main_pbt.py", line 126, in <module>
    main()
  File "/home/zhp/code/DB-Football/light_malib/main_pbt.py", line 114, in main
    runner.run()
  File "/home/zhp/code/DB-Football/light_malib/framework/pbt_runner.py", line 95, in run
    self.scheduler.initialize(self.cfg.populations)
  File "/home/zhp/code/DB-Football/light_malib/framework/scheduler/psro_scheduler.py", line 81, in initialize
    self.agent_manager.gen_new_policy(agent_id, self.population_id)
  File "/home/zhp/code/DB-Football/light_malib/agent/agent_manager.py", line 108, in gen_new_policy
    policy_id, policy = self.agents[agent_id].gen_new_policy(population_id)
  File "/home/zhp/code/DB-Football/light_malib/agent/agent.py", line 70, in gen_new_policy
    policy_id, policy = population.gen_new_policy()
  File "/home/zhp/code/DB-Football/light_malib/agent/agent.py", line 131, in gen_new_policy
    policy_id, policy = self.policy_factory.gen_new_policy()
  File "/home/zhp/code/DB-Football/light_malib/agent/policy_factory.py", line 73, in gen_new_policy
    policy_id, policy = self.init(self.new_policy_ctr)
  File "/home/zhp/code/DB-Football/light_malib/agent/policy_factory.py", line 117, in init
    pid, policy = self.init_from_random(
  File "/home/zhp/code/DB-Football/light_malib/agent/policy_factory.py", line 219, in init_from_random
    policy = policy_cls(
  File "/home/zhp/code/DB-Football/light_malib/algorithm/mappo/policy.py", line 127, in __init__
    actor = model.Actor(
  File "/home/zhp/code/DB-Football/light_malib/model/gr_football/basic_5/__init__.py", line 31, in __init__
    super().__init__(
  File "/home/zhp/code/DB-Football/light_malib/algorithm/common/rnn_net.py", line 35, in __init__
    self.base = get_model(model_config)(
  File "/home/zhp/code/DB-Football/light_malib/algorithm/common/model.py", line 208, in builder
    model = handler(
  File "/home/zhp/code/DB-Football/light_malib/algorithm/common/model.py", line 90, in __init__
    self._feature_norm = nn.LayerNorm(self.input_dim)
  File "/home/zhp/miniconda3/envs/football/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 155, in __init__
    self.normalized_shape = tuple(normalized_shape)  # type: ignore[arg-type]
TypeError: 'Box' object is not iterable

**Comment by 945716994** [comment]
I slove this problem by change the gymnasium to gym.
